// Code generated by go-swagger; DO NOT EDIT.

package hub

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"github.com/qlcchain/go-sonata-server/models"
)

// ProductOrderManagementHubDeleteHandlerFunc turns a function with the right signature into a product order management hub delete handler
type ProductOrderManagementHubDeleteHandlerFunc func(ProductOrderManagementHubDeleteParams, *models.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn ProductOrderManagementHubDeleteHandlerFunc) Handle(params ProductOrderManagementHubDeleteParams, principal *models.Principal) middleware.Responder {
	return fn(params, principal)
}

// ProductOrderManagementHubDeleteHandler interface for that can handle valid product order management hub delete params
type ProductOrderManagementHubDeleteHandler interface {
	Handle(ProductOrderManagementHubDeleteParams, *models.Principal) middleware.Responder
}

// NewProductOrderManagementHubDelete creates a new http.Handler for the product order management hub delete operation
func NewProductOrderManagementHubDelete(ctx *middleware.Context, handler ProductOrderManagementHubDeleteHandler) *ProductOrderManagementHubDelete {
	return &ProductOrderManagementHubDelete{Context: ctx, Handler: handler}
}

/* ProductOrderManagementHubDelete swagger:route DELETE /productOrderManagement/v3/hub/{HubId} Hub productOrderManagementHubDelete

Delete a Hub

Delete Hub

*/
type ProductOrderManagementHubDelete struct {
	Context *middleware.Context
	Handler ProductOrderManagementHubDeleteHandler
}

func (o *ProductOrderManagementHubDelete) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewProductOrderManagementHubDeleteParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal *models.Principal
	if uprinc != nil {
		principal = uprinc.(*models.Principal) // this is really a models.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
