// Code generated by go-swagger; DO NOT EDIT.

package product_order

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"github.com/qlcchain/go-sonata-server/models"
)

// ProductOrderFindHandlerFunc turns a function with the right signature into a product order find handler
type ProductOrderFindHandlerFunc func(ProductOrderFindParams, *models.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn ProductOrderFindHandlerFunc) Handle(params ProductOrderFindParams, principal *models.Principal) middleware.Responder {
	return fn(params, principal)
}

// ProductOrderFindHandler interface for that can handle valid product order find params
type ProductOrderFindHandler interface {
	Handle(ProductOrderFindParams, *models.Principal) middleware.Responder
}

// NewProductOrderFind creates a new http.Handler for the product order find operation
func NewProductOrderFind(ctx *middleware.Context, handler ProductOrderFindHandler) *ProductOrderFind {
	return &ProductOrderFind{Context: ctx, Handler: handler}
}

/* ProductOrderFind swagger:route GET /productOrderManagement/v3/productOrder ProductOrder productOrderFind

Find a list of product order(s)

This operation is used to retrieve one or more product orders based upon filter criteria specified on input.

*/
type ProductOrderFind struct {
	Context *middleware.Context
	Handler ProductOrderFindHandler
}

func (o *ProductOrderFind) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewProductOrderFindParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal *models.Principal
	if uprinc != nil {
		principal = uprinc.(*models.Principal) // this is really a models.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
