// Code generated by go-swagger; DO NOT EDIT.

package notification

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/qlcchain/go-sonata-server/models"
)

// NewNotificationQuoteCreationNotificationParams creates a new NotificationQuoteCreationNotificationParams object
// with the default values initialized.
func NewNotificationQuoteCreationNotificationParams() *NotificationQuoteCreationNotificationParams {
	var ()
	return &NotificationQuoteCreationNotificationParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewNotificationQuoteCreationNotificationParamsWithTimeout creates a new NotificationQuoteCreationNotificationParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewNotificationQuoteCreationNotificationParamsWithTimeout(timeout time.Duration) *NotificationQuoteCreationNotificationParams {
	var ()
	return &NotificationQuoteCreationNotificationParams{

		timeout: timeout,
	}
}

// NewNotificationQuoteCreationNotificationParamsWithContext creates a new NotificationQuoteCreationNotificationParams object
// with the default values initialized, and the ability to set a context for a request
func NewNotificationQuoteCreationNotificationParamsWithContext(ctx context.Context) *NotificationQuoteCreationNotificationParams {
	var ()
	return &NotificationQuoteCreationNotificationParams{

		Context: ctx,
	}
}

// NewNotificationQuoteCreationNotificationParamsWithHTTPClient creates a new NotificationQuoteCreationNotificationParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewNotificationQuoteCreationNotificationParamsWithHTTPClient(client *http.Client) *NotificationQuoteCreationNotificationParams {
	var ()
	return &NotificationQuoteCreationNotificationParams{
		HTTPClient: client,
	}
}

/*NotificationQuoteCreationNotificationParams contains all the parameters to send to the API endpoint
for the notification quote creation notification operation typically these are written to a http.Request
*/
type NotificationQuoteCreationNotificationParams struct {

	/*QuoteCreationNotification*/
	QuoteCreationNotification models.Event

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the notification quote creation notification params
func (o *NotificationQuoteCreationNotificationParams) WithTimeout(timeout time.Duration) *NotificationQuoteCreationNotificationParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the notification quote creation notification params
func (o *NotificationQuoteCreationNotificationParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the notification quote creation notification params
func (o *NotificationQuoteCreationNotificationParams) WithContext(ctx context.Context) *NotificationQuoteCreationNotificationParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the notification quote creation notification params
func (o *NotificationQuoteCreationNotificationParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the notification quote creation notification params
func (o *NotificationQuoteCreationNotificationParams) WithHTTPClient(client *http.Client) *NotificationQuoteCreationNotificationParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the notification quote creation notification params
func (o *NotificationQuoteCreationNotificationParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithQuoteCreationNotification adds the quoteCreationNotification to the notification quote creation notification params
func (o *NotificationQuoteCreationNotificationParams) WithQuoteCreationNotification(quoteCreationNotification models.Event) *NotificationQuoteCreationNotificationParams {
	o.SetQuoteCreationNotification(quoteCreationNotification)
	return o
}

// SetQuoteCreationNotification adds the quoteCreationNotification to the notification quote creation notification params
func (o *NotificationQuoteCreationNotificationParams) SetQuoteCreationNotification(quoteCreationNotification models.Event) {
	o.QuoteCreationNotification = quoteCreationNotification
}

// WriteToRequest writes these params to a swagger request
func (o *NotificationQuoteCreationNotificationParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if err := r.SetBodyParam(o.QuoteCreationNotification); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
