// Code generated by go-swagger; DO NOT EDIT.

package notification

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/qlcchain/go-sonata-server/models"
)

// NotificationProductOrderCreationNotificationReader is a Reader for the NotificationProductOrderCreationNotification structure.
type NotificationProductOrderCreationNotificationReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *NotificationProductOrderCreationNotificationReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewNotificationProductOrderCreationNotificationNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewNotificationProductOrderCreationNotificationBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewNotificationProductOrderCreationNotificationUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewNotificationProductOrderCreationNotificationForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewNotificationProductOrderCreationNotificationNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 405:
		result := NewNotificationProductOrderCreationNotificationMethodNotAllowed()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 408:
		result := NewNotificationProductOrderCreationNotificationRequestTimeout()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 422:
		result := NewNotificationProductOrderCreationNotificationUnprocessableEntity()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewNotificationProductOrderCreationNotificationInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 503:
		result := NewNotificationProductOrderCreationNotificationServiceUnavailable()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewNotificationProductOrderCreationNotificationNoContent creates a NotificationProductOrderCreationNotificationNoContent with default headers values
func NewNotificationProductOrderCreationNotificationNoContent() *NotificationProductOrderCreationNotificationNoContent {
	return &NotificationProductOrderCreationNotificationNoContent{}
}

/* NotificationProductOrderCreationNotificationNoContent describes a response with status code 204, with default header values.

No Content
*/
type NotificationProductOrderCreationNotificationNoContent struct {
}

func (o *NotificationProductOrderCreationNotificationNoContent) Error() string {
	return fmt.Sprintf("[POST /productOrderNotification/v3/notification/productOrderCreationNotification][%d] notificationProductOrderCreationNotificationNoContent ", 204)
}

func (o *NotificationProductOrderCreationNotificationNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewNotificationProductOrderCreationNotificationBadRequest creates a NotificationProductOrderCreationNotificationBadRequest with default headers values
func NewNotificationProductOrderCreationNotificationBadRequest() *NotificationProductOrderCreationNotificationBadRequest {
	return &NotificationProductOrderCreationNotificationBadRequest{}
}

/* NotificationProductOrderCreationNotificationBadRequest describes a response with status code 400, with default header values.

 Bad Request

List of supported error codes:
- 20: Invalid URL parameter value
- 21: Missing body
- 22: Invalid body
- 23: Missing body field
- 24: Invalid body field
- 25: Missing header
- 26: Invalid header value
- 27: Missing query-string parameter
- 28: Invalid query-string parameter value
*/
type NotificationProductOrderCreationNotificationBadRequest struct {
	Payload *models.ErrorRepresentation
}

func (o *NotificationProductOrderCreationNotificationBadRequest) Error() string {
	return fmt.Sprintf("[POST /productOrderNotification/v3/notification/productOrderCreationNotification][%d] notificationProductOrderCreationNotificationBadRequest  %+v", 400, o.Payload)
}
func (o *NotificationProductOrderCreationNotificationBadRequest) GetPayload() *models.ErrorRepresentation {
	return o.Payload
}

func (o *NotificationProductOrderCreationNotificationBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorRepresentation)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewNotificationProductOrderCreationNotificationUnauthorized creates a NotificationProductOrderCreationNotificationUnauthorized with default headers values
func NewNotificationProductOrderCreationNotificationUnauthorized() *NotificationProductOrderCreationNotificationUnauthorized {
	return &NotificationProductOrderCreationNotificationUnauthorized{}
}

/* NotificationProductOrderCreationNotificationUnauthorized describes a response with status code 401, with default header values.

 Unauthorized

List of supported error codes:
- 40: Missing credentials
- 41: Invalid credentials
- 42: Expired credentials
*/
type NotificationProductOrderCreationNotificationUnauthorized struct {
	Payload *models.ErrorRepresentation
}

func (o *NotificationProductOrderCreationNotificationUnauthorized) Error() string {
	return fmt.Sprintf("[POST /productOrderNotification/v3/notification/productOrderCreationNotification][%d] notificationProductOrderCreationNotificationUnauthorized  %+v", 401, o.Payload)
}
func (o *NotificationProductOrderCreationNotificationUnauthorized) GetPayload() *models.ErrorRepresentation {
	return o.Payload
}

func (o *NotificationProductOrderCreationNotificationUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorRepresentation)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewNotificationProductOrderCreationNotificationForbidden creates a NotificationProductOrderCreationNotificationForbidden with default headers values
func NewNotificationProductOrderCreationNotificationForbidden() *NotificationProductOrderCreationNotificationForbidden {
	return &NotificationProductOrderCreationNotificationForbidden{}
}

/* NotificationProductOrderCreationNotificationForbidden describes a response with status code 403, with default header values.

 Forbidden

List of supported error codes:
- 50: Access denied
- 51: Forbidden requester
- 52: Forbidden user
- 53: Too many requests
*/
type NotificationProductOrderCreationNotificationForbidden struct {
	Payload *models.ErrorRepresentation
}

func (o *NotificationProductOrderCreationNotificationForbidden) Error() string {
	return fmt.Sprintf("[POST /productOrderNotification/v3/notification/productOrderCreationNotification][%d] notificationProductOrderCreationNotificationForbidden  %+v", 403, o.Payload)
}
func (o *NotificationProductOrderCreationNotificationForbidden) GetPayload() *models.ErrorRepresentation {
	return o.Payload
}

func (o *NotificationProductOrderCreationNotificationForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorRepresentation)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewNotificationProductOrderCreationNotificationNotFound creates a NotificationProductOrderCreationNotificationNotFound with default headers values
func NewNotificationProductOrderCreationNotificationNotFound() *NotificationProductOrderCreationNotificationNotFound {
	return &NotificationProductOrderCreationNotificationNotFound{}
}

/* NotificationProductOrderCreationNotificationNotFound describes a response with status code 404, with default header values.

 Not Found

List of supported error codes:
- 60: Resource not found
*/
type NotificationProductOrderCreationNotificationNotFound struct {
	Payload *models.ErrorRepresentation
}

func (o *NotificationProductOrderCreationNotificationNotFound) Error() string {
	return fmt.Sprintf("[POST /productOrderNotification/v3/notification/productOrderCreationNotification][%d] notificationProductOrderCreationNotificationNotFound  %+v", 404, o.Payload)
}
func (o *NotificationProductOrderCreationNotificationNotFound) GetPayload() *models.ErrorRepresentation {
	return o.Payload
}

func (o *NotificationProductOrderCreationNotificationNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorRepresentation)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewNotificationProductOrderCreationNotificationMethodNotAllowed creates a NotificationProductOrderCreationNotificationMethodNotAllowed with default headers values
func NewNotificationProductOrderCreationNotificationMethodNotAllowed() *NotificationProductOrderCreationNotificationMethodNotAllowed {
	return &NotificationProductOrderCreationNotificationMethodNotAllowed{}
}

/* NotificationProductOrderCreationNotificationMethodNotAllowed describes a response with status code 405, with default header values.

 Method Not Allowed

List of supported error codes:
- 61: Method not allowed
*/
type NotificationProductOrderCreationNotificationMethodNotAllowed struct {
	Payload *models.ErrorRepresentation
}

func (o *NotificationProductOrderCreationNotificationMethodNotAllowed) Error() string {
	return fmt.Sprintf("[POST /productOrderNotification/v3/notification/productOrderCreationNotification][%d] notificationProductOrderCreationNotificationMethodNotAllowed  %+v", 405, o.Payload)
}
func (o *NotificationProductOrderCreationNotificationMethodNotAllowed) GetPayload() *models.ErrorRepresentation {
	return o.Payload
}

func (o *NotificationProductOrderCreationNotificationMethodNotAllowed) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorRepresentation)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewNotificationProductOrderCreationNotificationRequestTimeout creates a NotificationProductOrderCreationNotificationRequestTimeout with default headers values
func NewNotificationProductOrderCreationNotificationRequestTimeout() *NotificationProductOrderCreationNotificationRequestTimeout {
	return &NotificationProductOrderCreationNotificationRequestTimeout{}
}

/* NotificationProductOrderCreationNotificationRequestTimeout describes a response with status code 408, with default header values.

 Request Time-out

List of supported error codes:
- 63: Request time-out
*/
type NotificationProductOrderCreationNotificationRequestTimeout struct {
	Payload *models.ErrorRepresentation
}

func (o *NotificationProductOrderCreationNotificationRequestTimeout) Error() string {
	return fmt.Sprintf("[POST /productOrderNotification/v3/notification/productOrderCreationNotification][%d] notificationProductOrderCreationNotificationRequestTimeout  %+v", 408, o.Payload)
}
func (o *NotificationProductOrderCreationNotificationRequestTimeout) GetPayload() *models.ErrorRepresentation {
	return o.Payload
}

func (o *NotificationProductOrderCreationNotificationRequestTimeout) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorRepresentation)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewNotificationProductOrderCreationNotificationUnprocessableEntity creates a NotificationProductOrderCreationNotificationUnprocessableEntity with default headers values
func NewNotificationProductOrderCreationNotificationUnprocessableEntity() *NotificationProductOrderCreationNotificationUnprocessableEntity {
	return &NotificationProductOrderCreationNotificationUnprocessableEntity{}
}

/* NotificationProductOrderCreationNotificationUnprocessableEntity describes a response with status code 422, with default header values.

 Unprocessable entity

Functional error
*/
type NotificationProductOrderCreationNotificationUnprocessableEntity struct {
	Payload *models.ErrorRepresentation
}

func (o *NotificationProductOrderCreationNotificationUnprocessableEntity) Error() string {
	return fmt.Sprintf("[POST /productOrderNotification/v3/notification/productOrderCreationNotification][%d] notificationProductOrderCreationNotificationUnprocessableEntity  %+v", 422, o.Payload)
}
func (o *NotificationProductOrderCreationNotificationUnprocessableEntity) GetPayload() *models.ErrorRepresentation {
	return o.Payload
}

func (o *NotificationProductOrderCreationNotificationUnprocessableEntity) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorRepresentation)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewNotificationProductOrderCreationNotificationInternalServerError creates a NotificationProductOrderCreationNotificationInternalServerError with default headers values
func NewNotificationProductOrderCreationNotificationInternalServerError() *NotificationProductOrderCreationNotificationInternalServerError {
	return &NotificationProductOrderCreationNotificationInternalServerError{}
}

/* NotificationProductOrderCreationNotificationInternalServerError describes a response with status code 500, with default header values.

 Internal Server Error

List of supported error codes:
- 1: Internal error
*/
type NotificationProductOrderCreationNotificationInternalServerError struct {
	Payload *models.ErrorRepresentation
}

func (o *NotificationProductOrderCreationNotificationInternalServerError) Error() string {
	return fmt.Sprintf("[POST /productOrderNotification/v3/notification/productOrderCreationNotification][%d] notificationProductOrderCreationNotificationInternalServerError  %+v", 500, o.Payload)
}
func (o *NotificationProductOrderCreationNotificationInternalServerError) GetPayload() *models.ErrorRepresentation {
	return o.Payload
}

func (o *NotificationProductOrderCreationNotificationInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorRepresentation)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewNotificationProductOrderCreationNotificationServiceUnavailable creates a NotificationProductOrderCreationNotificationServiceUnavailable with default headers values
func NewNotificationProductOrderCreationNotificationServiceUnavailable() *NotificationProductOrderCreationNotificationServiceUnavailable {
	return &NotificationProductOrderCreationNotificationServiceUnavailable{}
}

/* NotificationProductOrderCreationNotificationServiceUnavailable describes a response with status code 503, with default header values.

Service Unavailable


*/
type NotificationProductOrderCreationNotificationServiceUnavailable struct {
	Payload *models.ErrorRepresentation
}

func (o *NotificationProductOrderCreationNotificationServiceUnavailable) Error() string {
	return fmt.Sprintf("[POST /productOrderNotification/v3/notification/productOrderCreationNotification][%d] notificationProductOrderCreationNotificationServiceUnavailable  %+v", 503, o.Payload)
}
func (o *NotificationProductOrderCreationNotificationServiceUnavailable) GetPayload() *models.ErrorRepresentation {
	return o.Payload
}

func (o *NotificationProductOrderCreationNotificationServiceUnavailable) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorRepresentation)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
