// Code generated by go-swagger; DO NOT EDIT.

package notification

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/qlcchain/go-sonata-server/models"
)

// NewNotificationProductOrderCreationNotificationParams creates a new NotificationProductOrderCreationNotificationParams object
// with the default values initialized.
func NewNotificationProductOrderCreationNotificationParams() *NotificationProductOrderCreationNotificationParams {
	var ()
	return &NotificationProductOrderCreationNotificationParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewNotificationProductOrderCreationNotificationParamsWithTimeout creates a new NotificationProductOrderCreationNotificationParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewNotificationProductOrderCreationNotificationParamsWithTimeout(timeout time.Duration) *NotificationProductOrderCreationNotificationParams {
	var ()
	return &NotificationProductOrderCreationNotificationParams{

		timeout: timeout,
	}
}

// NewNotificationProductOrderCreationNotificationParamsWithContext creates a new NotificationProductOrderCreationNotificationParams object
// with the default values initialized, and the ability to set a context for a request
func NewNotificationProductOrderCreationNotificationParamsWithContext(ctx context.Context) *NotificationProductOrderCreationNotificationParams {
	var ()
	return &NotificationProductOrderCreationNotificationParams{

		Context: ctx,
	}
}

// NewNotificationProductOrderCreationNotificationParamsWithHTTPClient creates a new NotificationProductOrderCreationNotificationParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewNotificationProductOrderCreationNotificationParamsWithHTTPClient(client *http.Client) *NotificationProductOrderCreationNotificationParams {
	var ()
	return &NotificationProductOrderCreationNotificationParams{
		HTTPClient: client,
	}
}

/*NotificationProductOrderCreationNotificationParams contains all the parameters to send to the API endpoint
for the notification product order creation notification operation typically these are written to a http.Request
*/
type NotificationProductOrderCreationNotificationParams struct {

	/*ProductOrderCreationNotification*/
	ProductOrderCreationNotification models.PoEvent

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the notification product order creation notification params
func (o *NotificationProductOrderCreationNotificationParams) WithTimeout(timeout time.Duration) *NotificationProductOrderCreationNotificationParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the notification product order creation notification params
func (o *NotificationProductOrderCreationNotificationParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the notification product order creation notification params
func (o *NotificationProductOrderCreationNotificationParams) WithContext(ctx context.Context) *NotificationProductOrderCreationNotificationParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the notification product order creation notification params
func (o *NotificationProductOrderCreationNotificationParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the notification product order creation notification params
func (o *NotificationProductOrderCreationNotificationParams) WithHTTPClient(client *http.Client) *NotificationProductOrderCreationNotificationParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the notification product order creation notification params
func (o *NotificationProductOrderCreationNotificationParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithProductOrderCreationNotification adds the productOrderCreationNotification to the notification product order creation notification params
func (o *NotificationProductOrderCreationNotificationParams) WithProductOrderCreationNotification(productOrderCreationNotification models.PoEvent) *NotificationProductOrderCreationNotificationParams {
	o.SetProductOrderCreationNotification(productOrderCreationNotification)
	return o
}

// SetProductOrderCreationNotification adds the productOrderCreationNotification to the notification product order creation notification params
func (o *NotificationProductOrderCreationNotificationParams) SetProductOrderCreationNotification(productOrderCreationNotification models.PoEvent) {
	o.ProductOrderCreationNotification = productOrderCreationNotification
}

// WriteToRequest writes these params to a swagger request
func (o *NotificationProductOrderCreationNotificationParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if err := r.SetBodyParam(o.ProductOrderCreationNotification); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
