// Code generated by go-swagger; DO NOT EDIT.

package notification

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/qlcchain/go-sonata-server/models"
)

// NewNotificationQuoteStateChangeNotificationParams creates a new NotificationQuoteStateChangeNotificationParams object
// with the default values initialized.
func NewNotificationQuoteStateChangeNotificationParams() *NotificationQuoteStateChangeNotificationParams {
	var ()
	return &NotificationQuoteStateChangeNotificationParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewNotificationQuoteStateChangeNotificationParamsWithTimeout creates a new NotificationQuoteStateChangeNotificationParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewNotificationQuoteStateChangeNotificationParamsWithTimeout(timeout time.Duration) *NotificationQuoteStateChangeNotificationParams {
	var ()
	return &NotificationQuoteStateChangeNotificationParams{

		timeout: timeout,
	}
}

// NewNotificationQuoteStateChangeNotificationParamsWithContext creates a new NotificationQuoteStateChangeNotificationParams object
// with the default values initialized, and the ability to set a context for a request
func NewNotificationQuoteStateChangeNotificationParamsWithContext(ctx context.Context) *NotificationQuoteStateChangeNotificationParams {
	var ()
	return &NotificationQuoteStateChangeNotificationParams{

		Context: ctx,
	}
}

// NewNotificationQuoteStateChangeNotificationParamsWithHTTPClient creates a new NotificationQuoteStateChangeNotificationParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewNotificationQuoteStateChangeNotificationParamsWithHTTPClient(client *http.Client) *NotificationQuoteStateChangeNotificationParams {
	var ()
	return &NotificationQuoteStateChangeNotificationParams{
		HTTPClient: client,
	}
}

/*NotificationQuoteStateChangeNotificationParams contains all the parameters to send to the API endpoint
for the notification quote state change notification operation typically these are written to a http.Request
*/
type NotificationQuoteStateChangeNotificationParams struct {

	/*QuoteStateChangeNotification*/
	QuoteStateChangeNotification models.Event

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the notification quote state change notification params
func (o *NotificationQuoteStateChangeNotificationParams) WithTimeout(timeout time.Duration) *NotificationQuoteStateChangeNotificationParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the notification quote state change notification params
func (o *NotificationQuoteStateChangeNotificationParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the notification quote state change notification params
func (o *NotificationQuoteStateChangeNotificationParams) WithContext(ctx context.Context) *NotificationQuoteStateChangeNotificationParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the notification quote state change notification params
func (o *NotificationQuoteStateChangeNotificationParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the notification quote state change notification params
func (o *NotificationQuoteStateChangeNotificationParams) WithHTTPClient(client *http.Client) *NotificationQuoteStateChangeNotificationParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the notification quote state change notification params
func (o *NotificationQuoteStateChangeNotificationParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithQuoteStateChangeNotification adds the quoteStateChangeNotification to the notification quote state change notification params
func (o *NotificationQuoteStateChangeNotificationParams) WithQuoteStateChangeNotification(quoteStateChangeNotification models.Event) *NotificationQuoteStateChangeNotificationParams {
	o.SetQuoteStateChangeNotification(quoteStateChangeNotification)
	return o
}

// SetQuoteStateChangeNotification adds the quoteStateChangeNotification to the notification quote state change notification params
func (o *NotificationQuoteStateChangeNotificationParams) SetQuoteStateChangeNotification(quoteStateChangeNotification models.Event) {
	o.QuoteStateChangeNotification = quoteStateChangeNotification
}

// WriteToRequest writes these params to a swagger request
func (o *NotificationQuoteStateChangeNotificationParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if err := r.SetBodyParam(o.QuoteStateChangeNotification); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
