before:
  hooks:
    # you may remove this if you don't use vgo
    - go mod download
    # you may remove this if you don't need go generate
    # - go generate ./...
builds:
  - id: gsonata-x64
    main: cmd/main.go
    binary: gsonata
    env:
      - CGO_ENABLED=0
    ldflags:
      - main.version={{.Version}} -X main.commit={{.ShortCommit}} -X main.date={{.Date}}
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64

archives:
- format: tar.gz
  format_overrides:
    - goos: windows
      format: zip
  name_template: "{{ .Binary }}-v{{ .Version }}-{{ .ShortCommit }}-{{ .Os }}-{{ .Arch }}"
  replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: SNAPSHOT-{{.ShortCommit}}

signs:
  -
    # name of the signature file.
    # '${artifact}' is the path to the artifact that should be signed.
    #
    # defaults to `${artifact}.sig`
    # signature: "${artifact}_sig"

    # command line arguments for the command
    #
    # to sign with a specific key use
    # args: ["-u", "<key id, fingerprint, email, ..>", "--output", "${signature}", "--detach-sign", "${artifact}"]
    #
    # defaults to `["--output", "${signature}", "--detach-sign", "${artifact}"]`
    args: ["-u", "QLCChain Bot (qlcchain-bot) <developers@qlink.mobi>", "--output", "${signature}", "--detach-sign", "${artifact}"]

    # which artifacts to sign
    #
    #   checksum: only checksum file(s)
    #   all:      all artifacts
    #   none:     no signing
    #
    # defaults to `none`
    artifacts: all
