// Code generated by go-swagger; DO NOT EDIT.

package quote

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// QuoteCreateHandlerFunc turns a function with the right signature into a quote create handler
type QuoteCreateHandlerFunc func(QuoteCreateParams) middleware.Responder

// Handle executing the request and returning a response
func (fn QuoteCreateHandlerFunc) Handle(params QuoteCreateParams) middleware.Responder {
	return fn(params)
}

// QuoteCreateHandler interface for that can handle valid quote create params
type QuoteCreateHandler interface {
	Handle(QuoteCreateParams) middleware.Responder
}

// NewQuoteCreate creates a new http.Handler for the quote create operation
func NewQuoteCreate(ctx *middleware.Context, handler QuoteCreateHandler) *QuoteCreate {
	return &QuoteCreate{Context: ctx, Handler: handler}
}

/*QuoteCreate swagger:route POST /quoteManagement/v2/quote Quote quoteCreate

Create a quote

This operation is used to create a new quote.

*/
type QuoteCreate struct {
	Context *middleware.Context
	Handler QuoteCreateHandler
}

func (o *QuoteCreate) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewQuoteCreateParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
