// Code generated by go-swagger; DO NOT EDIT.

package hub

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/qlcchain/go-sonata-server/models"
)

// ProductOrderManagementHubCreateReader is a Reader for the ProductOrderManagementHubCreate structure.
type ProductOrderManagementHubCreateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ProductOrderManagementHubCreateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewProductOrderManagementHubCreateCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewProductOrderManagementHubCreateBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewProductOrderManagementHubCreateUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewProductOrderManagementHubCreateForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewProductOrderManagementHubCreateNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 405:
		result := NewProductOrderManagementHubCreateMethodNotAllowed()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 408:
		result := NewProductOrderManagementHubCreateRequestTimeout()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 422:
		result := NewProductOrderManagementHubCreateUnprocessableEntity()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewProductOrderManagementHubCreateInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 503:
		result := NewProductOrderManagementHubCreateServiceUnavailable()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewProductOrderManagementHubCreateCreated creates a ProductOrderManagementHubCreateCreated with default headers values
func NewProductOrderManagementHubCreateCreated() *ProductOrderManagementHubCreateCreated {
	return &ProductOrderManagementHubCreateCreated{}
}

/*ProductOrderManagementHubCreateCreated handles this case with default header values.

Created
*/
type ProductOrderManagementHubCreateCreated struct {
	Payload *models.Hub
}

func (o *ProductOrderManagementHubCreateCreated) Error() string {
	return fmt.Sprintf("[POST /productOrderManagement/v3/hub][%d] productOrderManagementHubCreateCreated  %+v", 201, o.Payload)
}

func (o *ProductOrderManagementHubCreateCreated) GetPayload() *models.Hub {
	return o.Payload
}

func (o *ProductOrderManagementHubCreateCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Hub)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewProductOrderManagementHubCreateBadRequest creates a ProductOrderManagementHubCreateBadRequest with default headers values
func NewProductOrderManagementHubCreateBadRequest() *ProductOrderManagementHubCreateBadRequest {
	return &ProductOrderManagementHubCreateBadRequest{}
}

/*ProductOrderManagementHubCreateBadRequest handles this case with default header values.

Bad Request

List of supported error codes:
- 20: Invalid URL parameter value
- 21: Missing body
- 22: Invalid body
- 23: Missing body field
- 24: Invalid body field
- 25: Missing header
- 26: Invalid header value
- 27: Missing query-string parameter
- 28: Invalid query-string parameter value
*/
type ProductOrderManagementHubCreateBadRequest struct {
	Payload *models.ErrorRepresentation
}

func (o *ProductOrderManagementHubCreateBadRequest) Error() string {
	return fmt.Sprintf("[POST /productOrderManagement/v3/hub][%d] productOrderManagementHubCreateBadRequest  %+v", 400, o.Payload)
}

func (o *ProductOrderManagementHubCreateBadRequest) GetPayload() *models.ErrorRepresentation {
	return o.Payload
}

func (o *ProductOrderManagementHubCreateBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorRepresentation)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewProductOrderManagementHubCreateUnauthorized creates a ProductOrderManagementHubCreateUnauthorized with default headers values
func NewProductOrderManagementHubCreateUnauthorized() *ProductOrderManagementHubCreateUnauthorized {
	return &ProductOrderManagementHubCreateUnauthorized{}
}

/*ProductOrderManagementHubCreateUnauthorized handles this case with default header values.

Unauthorized

List of supported error codes:
- 40: Missing credentials
- 41: Invalid credentials
- 42: Expired credentials
*/
type ProductOrderManagementHubCreateUnauthorized struct {
	Payload *models.ErrorRepresentation
}

func (o *ProductOrderManagementHubCreateUnauthorized) Error() string {
	return fmt.Sprintf("[POST /productOrderManagement/v3/hub][%d] productOrderManagementHubCreateUnauthorized  %+v", 401, o.Payload)
}

func (o *ProductOrderManagementHubCreateUnauthorized) GetPayload() *models.ErrorRepresentation {
	return o.Payload
}

func (o *ProductOrderManagementHubCreateUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorRepresentation)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewProductOrderManagementHubCreateForbidden creates a ProductOrderManagementHubCreateForbidden with default headers values
func NewProductOrderManagementHubCreateForbidden() *ProductOrderManagementHubCreateForbidden {
	return &ProductOrderManagementHubCreateForbidden{}
}

/*ProductOrderManagementHubCreateForbidden handles this case with default header values.

Forbidden

List of supported error codes:
- 50: Access denied
- 51: Forbidden requester
- 52: Forbidden user
- 53: Too many requests
*/
type ProductOrderManagementHubCreateForbidden struct {
	Payload *models.ErrorRepresentation
}

func (o *ProductOrderManagementHubCreateForbidden) Error() string {
	return fmt.Sprintf("[POST /productOrderManagement/v3/hub][%d] productOrderManagementHubCreateForbidden  %+v", 403, o.Payload)
}

func (o *ProductOrderManagementHubCreateForbidden) GetPayload() *models.ErrorRepresentation {
	return o.Payload
}

func (o *ProductOrderManagementHubCreateForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorRepresentation)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewProductOrderManagementHubCreateNotFound creates a ProductOrderManagementHubCreateNotFound with default headers values
func NewProductOrderManagementHubCreateNotFound() *ProductOrderManagementHubCreateNotFound {
	return &ProductOrderManagementHubCreateNotFound{}
}

/*ProductOrderManagementHubCreateNotFound handles this case with default header values.

Not Found

List of supported error codes:
- 60: Resource not found
*/
type ProductOrderManagementHubCreateNotFound struct {
	Payload *models.ErrorRepresentation
}

func (o *ProductOrderManagementHubCreateNotFound) Error() string {
	return fmt.Sprintf("[POST /productOrderManagement/v3/hub][%d] productOrderManagementHubCreateNotFound  %+v", 404, o.Payload)
}

func (o *ProductOrderManagementHubCreateNotFound) GetPayload() *models.ErrorRepresentation {
	return o.Payload
}

func (o *ProductOrderManagementHubCreateNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorRepresentation)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewProductOrderManagementHubCreateMethodNotAllowed creates a ProductOrderManagementHubCreateMethodNotAllowed with default headers values
func NewProductOrderManagementHubCreateMethodNotAllowed() *ProductOrderManagementHubCreateMethodNotAllowed {
	return &ProductOrderManagementHubCreateMethodNotAllowed{}
}

/*ProductOrderManagementHubCreateMethodNotAllowed handles this case with default header values.

Method Not Allowed

List of supported error codes:
- 61: Method not allowed
*/
type ProductOrderManagementHubCreateMethodNotAllowed struct {
	Payload *models.ErrorRepresentation
}

func (o *ProductOrderManagementHubCreateMethodNotAllowed) Error() string {
	return fmt.Sprintf("[POST /productOrderManagement/v3/hub][%d] productOrderManagementHubCreateMethodNotAllowed  %+v", 405, o.Payload)
}

func (o *ProductOrderManagementHubCreateMethodNotAllowed) GetPayload() *models.ErrorRepresentation {
	return o.Payload
}

func (o *ProductOrderManagementHubCreateMethodNotAllowed) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorRepresentation)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewProductOrderManagementHubCreateRequestTimeout creates a ProductOrderManagementHubCreateRequestTimeout with default headers values
func NewProductOrderManagementHubCreateRequestTimeout() *ProductOrderManagementHubCreateRequestTimeout {
	return &ProductOrderManagementHubCreateRequestTimeout{}
}

/*ProductOrderManagementHubCreateRequestTimeout handles this case with default header values.

Request Time-out

List of supported error codes:
- 63: Request time-out
*/
type ProductOrderManagementHubCreateRequestTimeout struct {
	Payload *models.ErrorRepresentation
}

func (o *ProductOrderManagementHubCreateRequestTimeout) Error() string {
	return fmt.Sprintf("[POST /productOrderManagement/v3/hub][%d] productOrderManagementHubCreateRequestTimeout  %+v", 408, o.Payload)
}

func (o *ProductOrderManagementHubCreateRequestTimeout) GetPayload() *models.ErrorRepresentation {
	return o.Payload
}

func (o *ProductOrderManagementHubCreateRequestTimeout) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorRepresentation)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewProductOrderManagementHubCreateUnprocessableEntity creates a ProductOrderManagementHubCreateUnprocessableEntity with default headers values
func NewProductOrderManagementHubCreateUnprocessableEntity() *ProductOrderManagementHubCreateUnprocessableEntity {
	return &ProductOrderManagementHubCreateUnprocessableEntity{}
}

/*ProductOrderManagementHubCreateUnprocessableEntity handles this case with default header values.

Unprocessable entity

Functional error
*/
type ProductOrderManagementHubCreateUnprocessableEntity struct {
	Payload *models.ErrorRepresentation
}

func (o *ProductOrderManagementHubCreateUnprocessableEntity) Error() string {
	return fmt.Sprintf("[POST /productOrderManagement/v3/hub][%d] productOrderManagementHubCreateUnprocessableEntity  %+v", 422, o.Payload)
}

func (o *ProductOrderManagementHubCreateUnprocessableEntity) GetPayload() *models.ErrorRepresentation {
	return o.Payload
}

func (o *ProductOrderManagementHubCreateUnprocessableEntity) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorRepresentation)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewProductOrderManagementHubCreateInternalServerError creates a ProductOrderManagementHubCreateInternalServerError with default headers values
func NewProductOrderManagementHubCreateInternalServerError() *ProductOrderManagementHubCreateInternalServerError {
	return &ProductOrderManagementHubCreateInternalServerError{}
}

/*ProductOrderManagementHubCreateInternalServerError handles this case with default header values.

Internal Server Error

List of supported error codes:
- 1: Internal error
*/
type ProductOrderManagementHubCreateInternalServerError struct {
	Payload *models.ErrorRepresentation
}

func (o *ProductOrderManagementHubCreateInternalServerError) Error() string {
	return fmt.Sprintf("[POST /productOrderManagement/v3/hub][%d] productOrderManagementHubCreateInternalServerError  %+v", 500, o.Payload)
}

func (o *ProductOrderManagementHubCreateInternalServerError) GetPayload() *models.ErrorRepresentation {
	return o.Payload
}

func (o *ProductOrderManagementHubCreateInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorRepresentation)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewProductOrderManagementHubCreateServiceUnavailable creates a ProductOrderManagementHubCreateServiceUnavailable with default headers values
func NewProductOrderManagementHubCreateServiceUnavailable() *ProductOrderManagementHubCreateServiceUnavailable {
	return &ProductOrderManagementHubCreateServiceUnavailable{}
}

/*ProductOrderManagementHubCreateServiceUnavailable handles this case with default header values.

Service Unavailable


*/
type ProductOrderManagementHubCreateServiceUnavailable struct {
	Payload *models.ErrorRepresentation
}

func (o *ProductOrderManagementHubCreateServiceUnavailable) Error() string {
	return fmt.Sprintf("[POST /productOrderManagement/v3/hub][%d] productOrderManagementHubCreateServiceUnavailable  %+v", 503, o.Payload)
}

func (o *ProductOrderManagementHubCreateServiceUnavailable) GetPayload() *models.ErrorRepresentation {
	return o.Payload
}

func (o *ProductOrderManagementHubCreateServiceUnavailable) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorRepresentation)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
