// Code generated by go-swagger; DO NOT EDIT.

package hub

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/qlcchain/go-sonata-server/models"
)

// NewProductOrderManagementHubCreateParams creates a new ProductOrderManagementHubCreateParams object
// with the default values initialized.
func NewProductOrderManagementHubCreateParams() *ProductOrderManagementHubCreateParams {
	var ()
	return &ProductOrderManagementHubCreateParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewProductOrderManagementHubCreateParamsWithTimeout creates a new ProductOrderManagementHubCreateParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewProductOrderManagementHubCreateParamsWithTimeout(timeout time.Duration) *ProductOrderManagementHubCreateParams {
	var ()
	return &ProductOrderManagementHubCreateParams{

		timeout: timeout,
	}
}

// NewProductOrderManagementHubCreateParamsWithContext creates a new ProductOrderManagementHubCreateParams object
// with the default values initialized, and the ability to set a context for a request
func NewProductOrderManagementHubCreateParamsWithContext(ctx context.Context) *ProductOrderManagementHubCreateParams {
	var ()
	return &ProductOrderManagementHubCreateParams{

		Context: ctx,
	}
}

// NewProductOrderManagementHubCreateParamsWithHTTPClient creates a new ProductOrderManagementHubCreateParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewProductOrderManagementHubCreateParamsWithHTTPClient(client *http.Client) *ProductOrderManagementHubCreateParams {
	var ()
	return &ProductOrderManagementHubCreateParams{
		HTTPClient: client,
	}
}

/*ProductOrderManagementHubCreateParams contains all the parameters to send to the API endpoint
for the product order management hub create operation typically these are written to a http.Request
*/
type ProductOrderManagementHubCreateParams struct {

	/*Hub*/
	Hub *models.HubInput

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the product order management hub create params
func (o *ProductOrderManagementHubCreateParams) WithTimeout(timeout time.Duration) *ProductOrderManagementHubCreateParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the product order management hub create params
func (o *ProductOrderManagementHubCreateParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the product order management hub create params
func (o *ProductOrderManagementHubCreateParams) WithContext(ctx context.Context) *ProductOrderManagementHubCreateParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the product order management hub create params
func (o *ProductOrderManagementHubCreateParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the product order management hub create params
func (o *ProductOrderManagementHubCreateParams) WithHTTPClient(client *http.Client) *ProductOrderManagementHubCreateParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the product order management hub create params
func (o *ProductOrderManagementHubCreateParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithHub adds the hub to the product order management hub create params
func (o *ProductOrderManagementHubCreateParams) WithHub(hub *models.HubInput) *ProductOrderManagementHubCreateParams {
	o.SetHub(hub)
	return o
}

// SetHub adds the hub to the product order management hub create params
func (o *ProductOrderManagementHubCreateParams) SetHub(hub *models.HubInput) {
	o.Hub = hub
}

// WriteToRequest writes these params to a swagger request
func (o *ProductOrderManagementHubCreateParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Hub != nil {
		if err := r.SetBodyParam(o.Hub); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
