// Code generated by go-swagger; DO NOT EDIT.

package notification

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"github.com/qlcchain/go-sonata-server/models"
)

// NotificationProductOrderCreationNotificationHandlerFunc turns a function with the right signature into a notification product order creation notification handler
type NotificationProductOrderCreationNotificationHandlerFunc func(NotificationProductOrderCreationNotificationParams, *models.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn NotificationProductOrderCreationNotificationHandlerFunc) Handle(params NotificationProductOrderCreationNotificationParams, principal *models.Principal) middleware.Responder {
	return fn(params, principal)
}

// NotificationProductOrderCreationNotificationHandler interface for that can handle valid notification product order creation notification params
type NotificationProductOrderCreationNotificationHandler interface {
	Handle(NotificationProductOrderCreationNotificationParams, *models.Principal) middleware.Responder
}

// NewNotificationProductOrderCreationNotification creates a new http.Handler for the notification product order creation notification operation
func NewNotificationProductOrderCreationNotification(ctx *middleware.Context, handler NotificationProductOrderCreationNotificationHandler) *NotificationProductOrderCreationNotification {
	return &NotificationProductOrderCreationNotification{Context: ctx, Handler: handler}
}

/*NotificationProductOrderCreationNotification swagger:route POST /productOrderNotification/v3/notification/productOrderCreationNotification Notification notificationProductOrderCreationNotification

Product order creation notification structure

Product order creation notification structure description

*/
type NotificationProductOrderCreationNotification struct {
	Context *middleware.Context
	Handler NotificationProductOrderCreationNotificationHandler
}

func (o *NotificationProductOrderCreationNotification) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewNotificationProductOrderCreationNotificationParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal *models.Principal
	if uprinc != nil {
		principal = uprinc.(*models.Principal) // this is really a models.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
