// Code generated by go-swagger; DO NOT EDIT.

package geographic_address

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
)

// NewGeographicAddressGetParams creates a new GeographicAddressGetParams object
// no default values defined in spec.
func NewGeographicAddressGetParams() GeographicAddressGetParams {

	return GeographicAddressGetParams{}
}

// GeographicAddressGetParams contains all the bound params for the geographic address get operation
// typically these are obtained from a http.Request
//
// swagger:parameters geographicAddressGet
type GeographicAddressGetParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*
	  Required: true
	  In: path
	*/
	GeographicAddressID string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewGeographicAddressGetParams() beforehand.
func (o *GeographicAddressGetParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	rGeographicAddressID, rhkGeographicAddressID, _ := route.Params.GetOK("GeographicAddressId")
	if err := o.bindGeographicAddressID(rGeographicAddressID, rhkGeographicAddressID, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindGeographicAddressID binds and validates parameter GeographicAddressID from path.
func (o *GeographicAddressGetParams) bindGeographicAddressID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	o.GeographicAddressID = raw

	return nil
}
