// Code generated by go-swagger; DO NOT EDIT.

package geographic_site

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/qlcchain/go-sonata-server/models"
)

// GeographicSiteGetOKCode is the HTTP code returned for type GeographicSiteGetOK
const GeographicSiteGetOKCode int = 200

/*GeographicSiteGetOK Ok

swagger:response geographicSiteGetOK
*/
type GeographicSiteGetOK struct {

	/*
	  In: Body
	*/
	Payload *models.GeographicSite `json:"body,omitempty"`
}

// NewGeographicSiteGetOK creates GeographicSiteGetOK with default headers values
func NewGeographicSiteGetOK() *GeographicSiteGetOK {

	return &GeographicSiteGetOK{}
}

// WithPayload adds the payload to the geographic site get o k response
func (o *GeographicSiteGetOK) WithPayload(payload *models.GeographicSite) *GeographicSiteGetOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the geographic site get o k response
func (o *GeographicSiteGetOK) SetPayload(payload *models.GeographicSite) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GeographicSiteGetOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GeographicSiteGetBadRequestCode is the HTTP code returned for type GeographicSiteGetBadRequest
const GeographicSiteGetBadRequestCode int = 400

/*GeographicSiteGetBadRequest Bad Request

List of supported error codes:
- 20: Invalid URL parameter value
- 21: Missing body
- 22: Invalid body
- 23: Missing body field
- 24: Invalid body field
- 25: Missing header
- 26: Invalid header value
- 27: Missing query-string parameter
- 28: Invalid query-string parameter value

swagger:response geographicSiteGetBadRequest
*/
type GeographicSiteGetBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.ErrorRepresentation `json:"body,omitempty"`
}

// NewGeographicSiteGetBadRequest creates GeographicSiteGetBadRequest with default headers values
func NewGeographicSiteGetBadRequest() *GeographicSiteGetBadRequest {

	return &GeographicSiteGetBadRequest{}
}

// WithPayload adds the payload to the geographic site get bad request response
func (o *GeographicSiteGetBadRequest) WithPayload(payload *models.ErrorRepresentation) *GeographicSiteGetBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the geographic site get bad request response
func (o *GeographicSiteGetBadRequest) SetPayload(payload *models.ErrorRepresentation) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GeographicSiteGetBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GeographicSiteGetUnauthorizedCode is the HTTP code returned for type GeographicSiteGetUnauthorized
const GeographicSiteGetUnauthorizedCode int = 401

/*GeographicSiteGetUnauthorized Unauthorized

List of supported error codes:
- 40: Missing credentials
- 41: Invalid credentials
- 42: Expired credentials

swagger:response geographicSiteGetUnauthorized
*/
type GeographicSiteGetUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.ErrorRepresentation `json:"body,omitempty"`
}

// NewGeographicSiteGetUnauthorized creates GeographicSiteGetUnauthorized with default headers values
func NewGeographicSiteGetUnauthorized() *GeographicSiteGetUnauthorized {

	return &GeographicSiteGetUnauthorized{}
}

// WithPayload adds the payload to the geographic site get unauthorized response
func (o *GeographicSiteGetUnauthorized) WithPayload(payload *models.ErrorRepresentation) *GeographicSiteGetUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the geographic site get unauthorized response
func (o *GeographicSiteGetUnauthorized) SetPayload(payload *models.ErrorRepresentation) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GeographicSiteGetUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GeographicSiteGetNotFoundCode is the HTTP code returned for type GeographicSiteGetNotFound
const GeographicSiteGetNotFoundCode int = 404

/*GeographicSiteGetNotFound Not Found

List of supported error codes:
- 60: Resource not found

swagger:response geographicSiteGetNotFound
*/
type GeographicSiteGetNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.ErrorRepresentation `json:"body,omitempty"`
}

// NewGeographicSiteGetNotFound creates GeographicSiteGetNotFound with default headers values
func NewGeographicSiteGetNotFound() *GeographicSiteGetNotFound {

	return &GeographicSiteGetNotFound{}
}

// WithPayload adds the payload to the geographic site get not found response
func (o *GeographicSiteGetNotFound) WithPayload(payload *models.ErrorRepresentation) *GeographicSiteGetNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the geographic site get not found response
func (o *GeographicSiteGetNotFound) SetPayload(payload *models.ErrorRepresentation) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GeographicSiteGetNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GeographicSiteGetRequestTimeoutCode is the HTTP code returned for type GeographicSiteGetRequestTimeout
const GeographicSiteGetRequestTimeoutCode int = 408

/*GeographicSiteGetRequestTimeout Request Time-out

List of supported error codes:
- 63: Request time-out

swagger:response geographicSiteGetRequestTimeout
*/
type GeographicSiteGetRequestTimeout struct {

	/*
	  In: Body
	*/
	Payload *models.ErrorRepresentation `json:"body,omitempty"`
}

// NewGeographicSiteGetRequestTimeout creates GeographicSiteGetRequestTimeout with default headers values
func NewGeographicSiteGetRequestTimeout() *GeographicSiteGetRequestTimeout {

	return &GeographicSiteGetRequestTimeout{}
}

// WithPayload adds the payload to the geographic site get request timeout response
func (o *GeographicSiteGetRequestTimeout) WithPayload(payload *models.ErrorRepresentation) *GeographicSiteGetRequestTimeout {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the geographic site get request timeout response
func (o *GeographicSiteGetRequestTimeout) SetPayload(payload *models.ErrorRepresentation) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GeographicSiteGetRequestTimeout) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(408)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GeographicSiteGetUnprocessableEntityCode is the HTTP code returned for type GeographicSiteGetUnprocessableEntity
const GeographicSiteGetUnprocessableEntityCode int = 422

/*GeographicSiteGetUnprocessableEntity Unprocessable entity

Functional error

swagger:response geographicSiteGetUnprocessableEntity
*/
type GeographicSiteGetUnprocessableEntity struct {

	/*
	  In: Body
	*/
	Payload *models.ErrorRepresentation `json:"body,omitempty"`
}

// NewGeographicSiteGetUnprocessableEntity creates GeographicSiteGetUnprocessableEntity with default headers values
func NewGeographicSiteGetUnprocessableEntity() *GeographicSiteGetUnprocessableEntity {

	return &GeographicSiteGetUnprocessableEntity{}
}

// WithPayload adds the payload to the geographic site get unprocessable entity response
func (o *GeographicSiteGetUnprocessableEntity) WithPayload(payload *models.ErrorRepresentation) *GeographicSiteGetUnprocessableEntity {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the geographic site get unprocessable entity response
func (o *GeographicSiteGetUnprocessableEntity) SetPayload(payload *models.ErrorRepresentation) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GeographicSiteGetUnprocessableEntity) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(422)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GeographicSiteGetInternalServerErrorCode is the HTTP code returned for type GeographicSiteGetInternalServerError
const GeographicSiteGetInternalServerErrorCode int = 500

/*GeographicSiteGetInternalServerError Internal Server Error

List of supported error codes:
- 1: Internal error

swagger:response geographicSiteGetInternalServerError
*/
type GeographicSiteGetInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.ErrorRepresentation `json:"body,omitempty"`
}

// NewGeographicSiteGetInternalServerError creates GeographicSiteGetInternalServerError with default headers values
func NewGeographicSiteGetInternalServerError() *GeographicSiteGetInternalServerError {

	return &GeographicSiteGetInternalServerError{}
}

// WithPayload adds the payload to the geographic site get internal server error response
func (o *GeographicSiteGetInternalServerError) WithPayload(payload *models.ErrorRepresentation) *GeographicSiteGetInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the geographic site get internal server error response
func (o *GeographicSiteGetInternalServerError) SetPayload(payload *models.ErrorRepresentation) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GeographicSiteGetInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GeographicSiteGetServiceUnavailableCode is the HTTP code returned for type GeographicSiteGetServiceUnavailable
const GeographicSiteGetServiceUnavailableCode int = 503

/*GeographicSiteGetServiceUnavailable Service Unavailable



swagger:response geographicSiteGetServiceUnavailable
*/
type GeographicSiteGetServiceUnavailable struct {

	/*
	  In: Body
	*/
	Payload *models.ErrorRepresentation `json:"body,omitempty"`
}

// NewGeographicSiteGetServiceUnavailable creates GeographicSiteGetServiceUnavailable with default headers values
func NewGeographicSiteGetServiceUnavailable() *GeographicSiteGetServiceUnavailable {

	return &GeographicSiteGetServiceUnavailable{}
}

// WithPayload adds the payload to the geographic site get service unavailable response
func (o *GeographicSiteGetServiceUnavailable) WithPayload(payload *models.ErrorRepresentation) *GeographicSiteGetServiceUnavailable {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the geographic site get service unavailable response
func (o *GeographicSiteGetServiceUnavailable) SetPayload(payload *models.ErrorRepresentation) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GeographicSiteGetServiceUnavailable) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(503)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
