// Code generated by go-swagger; DO NOT EDIT.

package product

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"github.com/qlcchain/go-sonata-server/models"
)

// ProductFindHandlerFunc turns a function with the right signature into a product find handler
type ProductFindHandlerFunc func(ProductFindParams, *models.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn ProductFindHandlerFunc) Handle(params ProductFindParams, principal *models.Principal) middleware.Responder {
	return fn(params, principal)
}

// ProductFindHandler interface for that can handle valid product find params
type ProductFindHandler interface {
	Handle(ProductFindParams, *models.Principal) middleware.Responder
}

// NewProductFind creates a new http.Handler for the product find operation
func NewProductFind(ctx *middleware.Context, handler ProductFindHandler) *ProductFind {
	return &ProductFind{Context: ctx, Handler: handler}
}

/*ProductFind swagger:route GET /productInventoryManagement/v3/product Product productFind

productFind (list) - retrieve product list with summary view

The Buyer requests a list of Products from the Seller based on filter criteria.

*/
type ProductFind struct {
	Context *middleware.Context
	Handler ProductFindHandler
}

func (o *ProductFind) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewProductFindParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal *models.Principal
	if uprinc != nil {
		principal = uprinc.(*models.Principal) // this is really a models.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
