package schema

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"

	"github.com/qlcchain/go-sonata-server/models"
)

// StatusChange Holds the status modification reasons and associated date the status changed, populated by the server
//
// swagger:model StatusChange
type StatusChange struct {
	ID *string `json:"id"`

	// Date when the state changed
	// Format: date-time
	ChangeDate strfmt.DateTime `json:"changeDate,omitempty"`

	// Raison for which the state changed
	ChangeReason string `json:"changeReason,omitempty"`

	// status
	Status models.ProductStatus `json:"status,omitempty"`
}
