// Code generated by go-swagger; DO NOT EDIT.

package geographic_address_validation

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/qlcchain/go-sonata-server/models"
)

// GeographicAddressValidationCreateCreatedCode is the HTTP code returned for type GeographicAddressValidationCreateCreated
const GeographicAddressValidationCreateCreatedCode int = 201

/*GeographicAddressValidationCreateCreated Created

swagger:response geographicAddressValidationCreateCreated
*/
type GeographicAddressValidationCreateCreated struct {

	/*
	  In: Body
	*/
	Payload *models.GeographicAddressValidation `json:"body,omitempty"`
}

// NewGeographicAddressValidationCreateCreated creates GeographicAddressValidationCreateCreated with default headers values
func NewGeographicAddressValidationCreateCreated() *GeographicAddressValidationCreateCreated {

	return &GeographicAddressValidationCreateCreated{}
}

// WithPayload adds the payload to the geographic address validation create created response
func (o *GeographicAddressValidationCreateCreated) WithPayload(payload *models.GeographicAddressValidation) *GeographicAddressValidationCreateCreated {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the geographic address validation create created response
func (o *GeographicAddressValidationCreateCreated) SetPayload(payload *models.GeographicAddressValidation) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GeographicAddressValidationCreateCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(201)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GeographicAddressValidationCreateBadRequestCode is the HTTP code returned for type GeographicAddressValidationCreateBadRequest
const GeographicAddressValidationCreateBadRequestCode int = 400

/*GeographicAddressValidationCreateBadRequest Bad Request

List of supported error codes:
- 20: Invalid URL parameter value
- 21: Missing body
- 22: Invalid body
- 23: Missing body field
- 24: Invalid body field
- 25: Missing header
- 26: Invalid header value
- 27: Missing query-string parameter
- 28: Invalid query-string parameter value

swagger:response geographicAddressValidationCreateBadRequest
*/
type GeographicAddressValidationCreateBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.ErrorRepresentation `json:"body,omitempty"`
}

// NewGeographicAddressValidationCreateBadRequest creates GeographicAddressValidationCreateBadRequest with default headers values
func NewGeographicAddressValidationCreateBadRequest() *GeographicAddressValidationCreateBadRequest {

	return &GeographicAddressValidationCreateBadRequest{}
}

// WithPayload adds the payload to the geographic address validation create bad request response
func (o *GeographicAddressValidationCreateBadRequest) WithPayload(payload *models.ErrorRepresentation) *GeographicAddressValidationCreateBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the geographic address validation create bad request response
func (o *GeographicAddressValidationCreateBadRequest) SetPayload(payload *models.ErrorRepresentation) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GeographicAddressValidationCreateBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GeographicAddressValidationCreateUnauthorizedCode is the HTTP code returned for type GeographicAddressValidationCreateUnauthorized
const GeographicAddressValidationCreateUnauthorizedCode int = 401

/*GeographicAddressValidationCreateUnauthorized Unauthorized

List of supported error codes:
- 40: Missing credentials
- 41: Invalid credentials
- 42: Expired credentials

swagger:response geographicAddressValidationCreateUnauthorized
*/
type GeographicAddressValidationCreateUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.ErrorRepresentation `json:"body,omitempty"`
}

// NewGeographicAddressValidationCreateUnauthorized creates GeographicAddressValidationCreateUnauthorized with default headers values
func NewGeographicAddressValidationCreateUnauthorized() *GeographicAddressValidationCreateUnauthorized {

	return &GeographicAddressValidationCreateUnauthorized{}
}

// WithPayload adds the payload to the geographic address validation create unauthorized response
func (o *GeographicAddressValidationCreateUnauthorized) WithPayload(payload *models.ErrorRepresentation) *GeographicAddressValidationCreateUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the geographic address validation create unauthorized response
func (o *GeographicAddressValidationCreateUnauthorized) SetPayload(payload *models.ErrorRepresentation) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GeographicAddressValidationCreateUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GeographicAddressValidationCreateForbiddenCode is the HTTP code returned for type GeographicAddressValidationCreateForbidden
const GeographicAddressValidationCreateForbiddenCode int = 403

/*GeographicAddressValidationCreateForbidden Forbidden

List of supported error codes:
- 50: Access denied
- 51: Forbidden requester
- 52: Forbidden user
- 53: Too many requests

swagger:response geographicAddressValidationCreateForbidden
*/
type GeographicAddressValidationCreateForbidden struct {

	/*
	  In: Body
	*/
	Payload *models.ErrorRepresentation `json:"body,omitempty"`
}

// NewGeographicAddressValidationCreateForbidden creates GeographicAddressValidationCreateForbidden with default headers values
func NewGeographicAddressValidationCreateForbidden() *GeographicAddressValidationCreateForbidden {

	return &GeographicAddressValidationCreateForbidden{}
}

// WithPayload adds the payload to the geographic address validation create forbidden response
func (o *GeographicAddressValidationCreateForbidden) WithPayload(payload *models.ErrorRepresentation) *GeographicAddressValidationCreateForbidden {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the geographic address validation create forbidden response
func (o *GeographicAddressValidationCreateForbidden) SetPayload(payload *models.ErrorRepresentation) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GeographicAddressValidationCreateForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GeographicAddressValidationCreateNotFoundCode is the HTTP code returned for type GeographicAddressValidationCreateNotFound
const GeographicAddressValidationCreateNotFoundCode int = 404

/*GeographicAddressValidationCreateNotFound Not Found

List of supported error codes:
- 60: Resource not found

swagger:response geographicAddressValidationCreateNotFound
*/
type GeographicAddressValidationCreateNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.ErrorRepresentation `json:"body,omitempty"`
}

// NewGeographicAddressValidationCreateNotFound creates GeographicAddressValidationCreateNotFound with default headers values
func NewGeographicAddressValidationCreateNotFound() *GeographicAddressValidationCreateNotFound {

	return &GeographicAddressValidationCreateNotFound{}
}

// WithPayload adds the payload to the geographic address validation create not found response
func (o *GeographicAddressValidationCreateNotFound) WithPayload(payload *models.ErrorRepresentation) *GeographicAddressValidationCreateNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the geographic address validation create not found response
func (o *GeographicAddressValidationCreateNotFound) SetPayload(payload *models.ErrorRepresentation) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GeographicAddressValidationCreateNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GeographicAddressValidationCreateMethodNotAllowedCode is the HTTP code returned for type GeographicAddressValidationCreateMethodNotAllowed
const GeographicAddressValidationCreateMethodNotAllowedCode int = 405

/*GeographicAddressValidationCreateMethodNotAllowed Method Not Allowed

List of supported error codes:
- 61: Method not allowed

swagger:response geographicAddressValidationCreateMethodNotAllowed
*/
type GeographicAddressValidationCreateMethodNotAllowed struct {

	/*
	  In: Body
	*/
	Payload *models.ErrorRepresentation `json:"body,omitempty"`
}

// NewGeographicAddressValidationCreateMethodNotAllowed creates GeographicAddressValidationCreateMethodNotAllowed with default headers values
func NewGeographicAddressValidationCreateMethodNotAllowed() *GeographicAddressValidationCreateMethodNotAllowed {

	return &GeographicAddressValidationCreateMethodNotAllowed{}
}

// WithPayload adds the payload to the geographic address validation create method not allowed response
func (o *GeographicAddressValidationCreateMethodNotAllowed) WithPayload(payload *models.ErrorRepresentation) *GeographicAddressValidationCreateMethodNotAllowed {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the geographic address validation create method not allowed response
func (o *GeographicAddressValidationCreateMethodNotAllowed) SetPayload(payload *models.ErrorRepresentation) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GeographicAddressValidationCreateMethodNotAllowed) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(405)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GeographicAddressValidationCreateUnprocessableEntityCode is the HTTP code returned for type GeographicAddressValidationCreateUnprocessableEntity
const GeographicAddressValidationCreateUnprocessableEntityCode int = 422

/*GeographicAddressValidationCreateUnprocessableEntity Unprocessable entity

Functional error





 - code: 100
message: Too many addresses match - please re-try with more attribute values restriction
description:

swagger:response geographicAddressValidationCreateUnprocessableEntity
*/
type GeographicAddressValidationCreateUnprocessableEntity struct {

	/*
	  In: Body
	*/
	Payload *models.ErrorRepresentation `json:"body,omitempty"`
}

// NewGeographicAddressValidationCreateUnprocessableEntity creates GeographicAddressValidationCreateUnprocessableEntity with default headers values
func NewGeographicAddressValidationCreateUnprocessableEntity() *GeographicAddressValidationCreateUnprocessableEntity {

	return &GeographicAddressValidationCreateUnprocessableEntity{}
}

// WithPayload adds the payload to the geographic address validation create unprocessable entity response
func (o *GeographicAddressValidationCreateUnprocessableEntity) WithPayload(payload *models.ErrorRepresentation) *GeographicAddressValidationCreateUnprocessableEntity {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the geographic address validation create unprocessable entity response
func (o *GeographicAddressValidationCreateUnprocessableEntity) SetPayload(payload *models.ErrorRepresentation) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GeographicAddressValidationCreateUnprocessableEntity) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(422)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GeographicAddressValidationCreateInternalServerErrorCode is the HTTP code returned for type GeographicAddressValidationCreateInternalServerError
const GeographicAddressValidationCreateInternalServerErrorCode int = 500

/*GeographicAddressValidationCreateInternalServerError Internal Server Error

List of supported error codes:
- 1: Internal error

swagger:response geographicAddressValidationCreateInternalServerError
*/
type GeographicAddressValidationCreateInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.ErrorRepresentation `json:"body,omitempty"`
}

// NewGeographicAddressValidationCreateInternalServerError creates GeographicAddressValidationCreateInternalServerError with default headers values
func NewGeographicAddressValidationCreateInternalServerError() *GeographicAddressValidationCreateInternalServerError {

	return &GeographicAddressValidationCreateInternalServerError{}
}

// WithPayload adds the payload to the geographic address validation create internal server error response
func (o *GeographicAddressValidationCreateInternalServerError) WithPayload(payload *models.ErrorRepresentation) *GeographicAddressValidationCreateInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the geographic address validation create internal server error response
func (o *GeographicAddressValidationCreateInternalServerError) SetPayload(payload *models.ErrorRepresentation) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GeographicAddressValidationCreateInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GeographicAddressValidationCreateServiceUnavailableCode is the HTTP code returned for type GeographicAddressValidationCreateServiceUnavailable
const GeographicAddressValidationCreateServiceUnavailableCode int = 503

/*GeographicAddressValidationCreateServiceUnavailable Service Unavailable



swagger:response geographicAddressValidationCreateServiceUnavailable
*/
type GeographicAddressValidationCreateServiceUnavailable struct {

	/*
	  In: Body
	*/
	Payload *models.ErrorRepresentation `json:"body,omitempty"`
}

// NewGeographicAddressValidationCreateServiceUnavailable creates GeographicAddressValidationCreateServiceUnavailable with default headers values
func NewGeographicAddressValidationCreateServiceUnavailable() *GeographicAddressValidationCreateServiceUnavailable {

	return &GeographicAddressValidationCreateServiceUnavailable{}
}

// WithPayload adds the payload to the geographic address validation create service unavailable response
func (o *GeographicAddressValidationCreateServiceUnavailable) WithPayload(payload *models.ErrorRepresentation) *GeographicAddressValidationCreateServiceUnavailable {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the geographic address validation create service unavailable response
func (o *GeographicAddressValidationCreateServiceUnavailable) SetPayload(payload *models.ErrorRepresentation) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GeographicAddressValidationCreateServiceUnavailable) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(503)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
