// Code generated by go-swagger; DO NOT EDIT.

package cancel_product_order

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"

	"github.com/qlcchain/go-sonata-server/models"
)

// NewCancelProductOrderCreateParams creates a new CancelProductOrderCreateParams object
// no default values defined in spec.
func NewCancelProductOrderCreateParams() CancelProductOrderCreateParams {

	return CancelProductOrderCreateParams{}
}

// CancelProductOrderCreateParams contains all the bound params for the cancel product order create operation
// typically these are obtained from a http.Request
//
// swagger:parameters cancelProductOrderCreate
type CancelProductOrderCreateParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*
	  Required: true
	  In: body
	*/
	CancelProductOrder *models.CancelProductOrderCreate
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewCancelProductOrderCreateParams() beforehand.
func (o *CancelProductOrderCreateParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body models.CancelProductOrderCreate
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			if err == io.EOF {
				res = append(res, errors.Required("cancelProductOrder", "body"))
			} else {
				res = append(res, errors.NewParseError("cancelProductOrder", "body", "", err))
			}
		} else {
			// validate body object
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.CancelProductOrder = &body
			}
		}
	} else {
		res = append(res, errors.Required("cancelProductOrder", "body"))
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
