// Code generated by go-swagger; DO NOT EDIT.

package cancel_product_order

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// CancelProductOrderCreateHandlerFunc turns a function with the right signature into a cancel product order create handler
type CancelProductOrderCreateHandlerFunc func(CancelProductOrderCreateParams) middleware.Responder

// Handle executing the request and returning a response
func (fn CancelProductOrderCreateHandlerFunc) Handle(params CancelProductOrderCreateParams) middleware.Responder {
	return fn(params)
}

// CancelProductOrderCreateHandler interface for that can handle valid cancel product order create params
type CancelProductOrderCreateHandler interface {
	Handle(CancelProductOrderCreateParams) middleware.Responder
}

// NewCancelProductOrderCreate creates a new http.Handler for the cancel product order create operation
func NewCancelProductOrderCreate(ctx *middleware.Context, handler CancelProductOrderCreateHandler) *CancelProductOrderCreate {
	return &CancelProductOrderCreate{Context: ctx, Handler: handler}
}

/*CancelProductOrderCreate swagger:route POST /productOrderManagement/v3/cancelProductOrder CancelProductOrder cancelProductOrderCreate

Create product order cancellation request

This operation allows buyer to request a product order cancellation request

*/
type CancelProductOrderCreate struct {
	Context *middleware.Context
	Handler CancelProductOrderCreateHandler
}

func (o *CancelProductOrderCreate) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewCancelProductOrderCreateParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
