name: Release

on: 
  release:
    types: [published]

jobs:

  release:
    name: Release artifacts and docker images
    runs-on: ubuntu-18.04
 
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.14.x
      
      - name: Generate changelog with git-chglog
        env:
          GIT_CHGLOG_VERION: 0.9.1
        run: |
          sudo wget -O /usr/local/bin/git-chglog https://github.com/git-chglog/git-chglog/releases/download/${GIT_CHGLOG_VERION}/git-chglog_linux_amd64
          sudo chmod +x /usr/local/bin/git-chglog
          export PATH=$PATH:/usr/local/bin
          export TAG=${GITHUB_REF/refs\/tags\//}
          make VERSION=${TAG} changelog
      
      - name: GoReleaser Action
        uses: goreleaser/goreleaser-action@v1.4.0
        with:
          version: latest
          args: release --rm-dist --release-notes=CHANGELOG.md
          key: ${{ secrets.PRIVATE_KEY }}
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      
      - name: Publish Docker image to DockerHub
        uses: docker://goreng/publish-docker-github-action:v2.4
        with:
          name: qlcchain/go-sonata-server
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          dockerfile: Dockerfile