// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"
)

// OrderActivity The type of order as defined by the business.
//
// swagger:model OrderActivity
type OrderActivity string

func NewOrderActivity(value OrderActivity) *OrderActivity {
	v := value
	return &v
}

const (

	// OrderActivityInstall captures enum value "install"
	OrderActivityInstall OrderActivity = "install"

	// OrderActivityChange captures enum value "change"
	OrderActivityChange OrderActivity = "change"

	// OrderActivityDisconnect captures enum value "disconnect"
	OrderActivityDisconnect OrderActivity = "disconnect"
)

// for schema
var orderActivityEnum []interface{}

func init() {
	var res []OrderActivity
	if err := json.Unmarshal([]byte(`["install","change","disconnect"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		orderActivityEnum = append(orderActivityEnum, v)
	}
}

func (m OrderActivity) validateOrderActivityEnum(path, location string, value OrderActivity) error {
	if err := validate.EnumCase(path, location, value, orderActivityEnum, true); err != nil {
		return err
	}
	return nil
}

// Validate validates this order activity
func (m OrderActivity) Validate(formats strfmt.Registry) error {
	var res []error

	// value enum
	if err := m.validateOrderActivityEnum("", "body", m); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// ContextValidate validates this order activity based on context it is used
func (m OrderActivity) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
